const UA='VJ3DSearch/1.3 (+https://github.com/vyiito/car3d-search)'
const API='https://3dsky.org/api/models'
const BASE='https://3dsky.org'
const IMAGE_BASE='https://b5.3dsky.org'
const YEAR_RE=/\b(19[3-9]\d|20[0-3]\d)\b/
const FORMAT_RE=/\b(fbx|obj|3ds|max|blend|c4d|dae|gltf|glb|stl|3mf)\b/gi
const BRANDS=['Abarth','Acura','Alfa Romeo','Alpine','Aston Martin','Audi','Bentley','BMW','Bugatti','Buick','BYD','Cadillac','Chevrolet','Citroen','Dodge','Ferrari','Fiat','Ford','Honda','Hyundai','Infiniti','Jaguar','Jeep','Kia','Koenigsegg','Lamborghini','Lancia','Land Rover','Lexus','Lotus','Maserati','Mazda','McLaren','Mercedes-Benz','Mercedes','Mini','Mitsubishi','Nissan','Opel','Pagani','Peugeot','Pontiac','Porsche','Renault','Subaru','Suzuki','Tesla','Toyota','Volkswagen','Volvo']
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
function brandOf(text){const n=norm(text);return BRANDS.find(b=>n.includes(norm(b)))||null}
function formatsOf(model){const text=[model?.properties?.platform?.titleEn,model?.properties?.platform?.title].filter(Boolean).join(' ');return [...new Set((text.match(FORMAT_RE)||[]).map(x=>x.toUpperCase()))]}
function imageOf(model){const path=model?.images?.[0]?.web_path;if(!path)return null;try{return new URL(path.replace(/^\/+/,''),`${IMAGE_BASE}/`).href}catch{return null}}
function isTransport(model){return model?.category_parent?.slug==='transport'||model?.category?.slug==='ground-transport'||/transport/i.test(`${model?.category_parent?.title_en||''} ${model?.category?.title_en||''}`)}
function vehicleClass(text){const n=norm(text);if(/\b(suv|crossover|4x4|off.?road)\b/.test(n))return 'SUV';if(/\b(race|racing|gt3|gt4|rally|drift|formula)\b/.test(n))return 'Race Car';if(/\b(truck|pickup|pick-up|lorry)\b/.test(n))return 'Truck / Pickup';if(/\b(bus|coach|minibus)\b/.test(n))return 'Bus';if(/\b(van|minivan|mpv)\b/.test(n))return 'Van';if(/\b(motorcycle|motorbike|scooter|bike)\b/.test(n))return 'Motorcycle';return 'Car'}
function sizeOf(bytes,kb){const value=Number(bytes||0)||Number(kb||0)*1024;if(!value)return null;const mb=value/1024/1024;return mb>=1024?`${(mb/1024).toFixed(1)} GB`:`${mb.toFixed(mb>=100?0:1)} MB`}
async function page(query,page){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(API,{method:'POST',signal:controller.signal,redirect:'follow',headers:{'user-agent':UA,accept:'application/json','content-type':'application/json','accept-language':'en-US,en;q=0.9'},body:JSON.stringify({query,order:'relevance',page,types:['free']})});if(!response.ok)throw new Error(`3DSky HTTP ${response.status}`);return await response.json()}finally{clearTimeout(timer)}}
export async function search3DSky(query,limit=60){const results=[],seen=new Set();let pagesFetched=0,totalPages=1;for(let p=1;p<=totalPages&&results.length<limit&&p<=8;p+=1){const payload=await page(query,p);pagesFetched+=1;const data=payload?.data||{};const models=Array.isArray(data.models)?data.models:[];const per=Math.max(1,Number(data.per_page||60)),total=Math.max(0,Number(data.total_value||0));totalPages=Math.min(8,Math.max(1,Math.ceil(total/per)));for(const model of models){if(results.length>=limit)break;if(model?.model_type!=='free'||!isTransport(model)||!model?.slug)continue;const title=String(model.title_en||model.title||'').trim();if(!title)continue;const url=`${BASE}/3dmodels/show/${encodeURIComponent(model.slug)}`;if(seen.has(url))continue;seen.add(url);const year=title.match(YEAR_RE)?.[1];results.push({id:`3dsky:${model.slug}`,title,source:'3DSky',sourceId:'3dsky',sourceType:'3d-models',sourceUrl:url,imageUrl:imageOf(model),formats:formatsOf(model),price:0,isFree:true,downloadable:null,downloadUrl:null,author:null,description:[model.category_parent?.title_en,model.category?.title_en,model.properties?.render?.title].filter(Boolean).join(' · ')||null,fileSize:sizeOf(model.data_file_size,model.properties?.size_kb),brand:brandOf(title),game:null,year:year?Number(year):null,vehicleClass:vehicleClass(title),score:10})}}
return{results,pagesFetched}}
