import * as cheerio from 'cheerio'

const UA='VJ3DSearch/2.3 (+https://github.com/vyiito/car3d-search)'
const YEAR_RE=/\b(19[3-9]\d|20[0-3]\d)\b/
const VEHICLE_WORDS=/\b(car|vehicle|automotive|coupe|sedan|hatch|wagon|suv|truck|pickup|racing|sport|supercar|roadster|convertible)\b/i
const BRANDS=['Abarth','Acura','Alfa Romeo','Alpine','Aston Martin','Audi','Bentley','BMW','Bugatti','BYD','Cadillac','Chevrolet','Dodge','Ferrari','Fiat','Ford','Funco Motorsports','Honda','Hyundai','Infiniti','Jaguar','Jeep','Kia','Koenigsegg','Lamborghini','Lancia','Land Rover','Lexus','Lotus','Maserati','Mazda','McLaren','Mercedes-Benz','Mercedes','Mini','Mitsubishi','Nissan','Pagani','Peugeot','Porsche','Renault','Rimac','Rolls-Royce','Subaru','Suzuki','Tesla','Toyota','Volkswagen','Volvo']
const clean=v=>String(v||'').replace(/\s+/g,' ').trim()
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const slug=v=>norm(v).replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')
const absolute=(value,base)=>{try{return value?new URL(value,base).href:null}catch{return null}}
function score(text,query){const source=norm(text),tokens=norm(query).split(/\s+/).filter(t=>t.length>1);if(!tokens.length)return 0;let value=0;for(const token of tokens)if(source.includes(token))value+=1;if(source.includes(norm(query)))value+=4;return value}
function brandOf(text){const n=norm(text);return BRANDS.find(b=>n.includes(norm(b)))||null}
function vehicleClass(text){const n=norm(text);if(/\b(suv|crossover|4x4|off.?road)\b/.test(n))return'SUV';if(/\b(race|racing|gt3|rally|drift|formula)\b/.test(n))return'Race Car';if(/\b(truck|pickup|pick-up)\b/.test(n))return'Truck / Pickup';if(/\b(van|minivan|mpv)\b/.test(n))return'Van';return'Car'}
function parseBalancedObject(text,start){let depth=0,inString=false,escaped=false;for(let i=start;i<text.length;i++){const c=text[i];if(inString){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')inString=false;continue}if(c==='"'){inString=true;continue}if(c==='{')depth++;else if(c==='}'){depth--;if(depth===0){try{return JSON.parse(text.slice(start,i+1))}catch{return null}}}}return null}
function extractListings(html){const rows=[],seen=new Set();const patterns=[/\{"id":"?[A-Za-z0-9_-]+"?,"type":"listingItem","attributes":\{/g,/\{\"id\":\"?[A-Za-z0-9_-]+\"?,\"type\":\"listingItem\",\"attributes\":\{/g];for(const re of patterns){let match;while((match=re.exec(html))&&rows.length<250){const obj=parseBalancedObject(html,match.index);if(obj?.type==='listingItem'&&obj?.attributes&&!seen.has(String(obj.attributes.id))){seen.add(String(obj.attributes.id));rows.push(obj.attributes)}re.lastIndex=Math.max(re.lastIndex,match.index+1)}}return rows}
async function fetchHtml(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const response=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'}});if(!response.ok)throw new Error(`CGTrader HTTP ${response.status}`);return await response.text()}finally{clearTimeout(timer)}}
function queryTag(query){const tokens=norm(query).split(/\s+/).filter(Boolean);const modelish=tokens.filter(t=>!['3d','model','car','vehicle'].includes(t));return slug(modelish.at(-1)||query)}
function fromListing(item,query){const base='https://www.cgtrader.com',title=clean(item?.title),sourceUrl=absolute(item?.url||item?.modelInfo?.modelUrl,base);if(!title||!sourceUrl)return null;const category=clean(`${item?.categorySlug||''} ${item?.categoryTitle||''} ${item?.subcategorySlug||''} ${item?.subcategoryTitle||''}`);const text=`${title} ${item?.description||''} ${category}`;if(score(text,query)<=0)return null;if(category&&!/\bcar\b|vehicle|transport/i.test(category)&&!VEHICLE_WORDS.test(text))return null;const rawPrice=Number(item?.price),price=Number.isFinite(rawPrice)?rawPrice:null,isFree=price===0?true:price!==null?false:null;const formats=Array.isArray(item?.metaverseFormatsList)?[...new Set(item.metaverseFormatsList.map(f=>String(f?.name||'').replace(/^\./,'').toUpperCase()).filter(Boolean))].slice(0,12):[];const types=item?.modelInfo?.types||{},signals=[types.pbr?'PBR':null,types.rigged?'Rigged':null,types.lowPoly?'Low poly':null,types.animated?'Animated':null,types.printReady?'Print ready':null].filter(Boolean);const description=clean(cheerio.load(String(item?.description||'')).text());const year=title.match(YEAR_RE)?.[1];return{id:`cgtrader:${item.id}`,title,source:'CGTrader',sourceId:'cgtrader',sourceType:'3d-models',sourceUrl,imageUrl:item?.primaryImage?.gridUrl||item?.primaryImage?.gridFallbackUrl||item?.schemaImageUrl||null,formats,price,isFree,priceLabel:isFree?'GRÁTIS':price!==null?`$${price.toFixed(price%1?2:0)}`:null,downloadable:null,downloadUrl:null,author:null,description:clean(`${description} ${signals.join(' ')}`).slice(0,520)||null,fileSize:null,brand:brandOf(title),game:null,year:year?Number(year):null,vehicleClass:vehicleClass(text),score:score(text,query)+8}}
export async function searchCGTraderMarketV2(query,limit=60){const tag=queryTag(query),routes=[`https://www.cgtrader.com/3d-models/${encodeURIComponent(tag)}`,`https://www.cgtrader.com/3d-models?keywords=${encodeURIComponent(query)}`],results=[],seen=new Set();let pagesFetched=0;for(const route of routes){for(let page=1;page<=6&&results.length<limit;page++){const url=new URL(route);if(page>1)url.searchParams.set('page',String(page));let html;try{html=await fetchHtml(url.href)}catch{break}pagesFetched++;const listings=extractListings(html);if(!listings.length)break;let added=0;for(const item of listings){const parsed=fromListing(item,query);if(!parsed||seen.has(parsed.sourceUrl))continue;seen.add(parsed.sourceUrl);results.push(parsed);added++;if(results.length>=limit)break}if(!added&&page>1)break}if(results.length)break}return{results:results.sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,limit),pagesFetched}}
