import * as cheerio from 'cheerio'
import pLimit from 'p-limit'

const UA='VJ3DSearch/1.6 (+https://github.com/vyiito/car3d-search)'
const BASE='https://www.overtake.gg'
const limiter=pLimit(5)
const YEAR_RE=/\b(19[3-9]\d|20[0-3]\d)\b/
const PRICE_RE=/(?:US\$|\$|€|£)\s?(\d+(?:[.,]\d{1,2})?)/i
const BRANDS=['Abarth','Acura','Alfa Romeo','Alpine','Aston Martin','Audi','Bentley','BMW','Bugatti','Cadillac','Chevrolet','Dodge','Ferrari','Fiat','Ford','Funco Motorsports','Honda','Hyundai','Infiniti','Jaguar','Jeep','Kia','Koenigsegg','Lamborghini','Lancia','Land Rover','Lexus','Lotus','Maserati','Mazda','McLaren','Mercedes-Benz','Mercedes','Mini','Mitsubishi','Nissan','Opel','Pagani','Peugeot','Pontiac','Porsche','Renault','Subaru','Suzuki','Tesla','Toyota','Volkswagen','Volvo']
const clean=v=>String(v||'').replace(/\s+/g,' ').trim()
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const slug=v=>norm(v).replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const esc=v=>v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')
function score(text,query){const s=norm(text),tokens=norm(query).split(/\s+/).filter(t=>t.length>1);let n=0;for(const t of tokens)if(s.includes(t))n++;if(s.includes(norm(query)))n+=4;return n}
function brandOf(text){const s=norm(text);return BRANDS.find(b=>new RegExp(`(^|[^a-z0-9])${esc(norm(b))}([^a-z0-9]|$)`,'i').test(s))||null}
function priceFrom(text){const match=clean(text).match(PRICE_RE);if(!match)return null;const value=Number(match[1].replace(',','.'));return Number.isFinite(value)?value:null}
async function fetchHtml(url,timeout=11000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'}});if(!r.ok)throw new Error(`OverTake HTTP ${r.status}`);return{html:await r.text(),finalUrl:r.url}}finally{clearTimeout(timer)}}
function tagCandidates(query){const full=slug(query),tokens=norm(query).split(/\s+/).filter(t=>t.length>2),out=[full];if(tokens.length>1)out.push(tokens.join('-'));const brand=BRANDS.find(b=>norm(query).includes(norm(b)));if(brand){const rest=tokens.filter(t=>!norm(brand).split(/\s+/).includes(t));if(rest.length)out.push(`${slug(brand)}-${rest.join('-')}`)}if(tokens.length)out.push(tokens[tokens.length-1]);return [...new Set(out.filter(Boolean))].slice(0,3)}
function parseTag(html,query){const $=cheerio.load(html),out=[],seen=new Set();$('a[href*="/downloads/"]').each((_,el)=>{const a=$(el);let url;try{url=new URL(a.attr('href'),BASE).href}catch{return}if(!url.startsWith(`${BASE}/downloads/`)||seen.has(url))return;const card=a.closest('article,li,[class*="contentRow"],[class*="structItem"],[class*="block-row"]').first();const title=clean(a.attr('title')||a.text()||card.find('h1,h2,h3,h4').first().text());const text=clean(`${title} ${card.text()}`);if(!title||score(text,query)<=0)return;seen.add(url);const img=card.find('img').first().attr('src')||card.find('img').first().attr('data-src')||null;let imageUrl=null;try{if(img)imageUrl=new URL(img,url).href}catch{}out.push({title,sourceUrl:url,imageUrl,relevance:score(text,query)})});return out}
function inferGame(text){const n=norm(text);if(/assetto corsa rally|\bacr\b/.test(n))return 'Assetto Corsa Rally';if(/assetto corsa competizione|\bacc\b/.test(n))return 'Assetto Corsa Competizione';if(/assetto corsa evo|\bace\b/.test(n))return 'Assetto Corsa EVO';if(/assetto corsa|\bac cars\b/.test(n))return 'Assetto Corsa';if(/beamng/.test(n))return 'BeamNG.drive';if(/automobilista 2|ams 2/.test(n))return 'Automobilista 2';if(/rfactor 2/.test(n))return 'rFactor 2';return null}
function isVehicleCategory(text){return /\b(?:AC|ACE|ACR|AMS\s*2|BeamNG|rFactor\s*2)?\s*(?:Cars|Vehicles)\b/i.test(text)&&!/(?:Skins?|Liver(?:y|ies)|Sounds?|Tracks?|Apps?|Misc|Career|Templates?)/i.test(text)}
async function enrich(candidate){try{const{html}=await fetchHtml(candidate.sourceUrl),$=cheerio.load(html),body=clean($('body').text()),title=clean($('h1').first().text())||candidate.title;if(/\[Deleted\]|no longer available for download|resource has been removed/i.test(`${title} ${body}`))return null;if(!isVehicleCategory(body.slice(0,10000)))return null;const description=clean($('.bbWrapper,.resourceBody,[class*="resourceBody"]').first().text()).slice(0,520)||null;const og=$('meta[property="og:image"]').attr('content')||candidate.imageUrl||null;const author=clean($('a[href*="/members/"]').first().text())||null;const yearMatch=`${title} ${description||''}`.match(YEAR_RE);const game=inferGame(body);const parsedPrice=priceFrom(body.slice(0,9000));const explicitFree=/\bfree\b/i.test(body.slice(0,7000))||/0[.,]00/.test(body.slice(0,7000));const isFree=parsedPrice===0||explicitFree&&!(parsedPrice&&parsedPrice>0);const paid=parsedPrice!==null&&parsedPrice>0;return{id:`overtake:${Buffer.from(candidate.sourceUrl).toString('base64url').slice(0,28)}`,title,source:'OverTake.gg',sourceId:'overtake',sourceType:'game-mods',sourceUrl:candidate.sourceUrl,imageUrl:og,formats:[],price:isFree?0:parsedPrice,isFree:isFree?true:paid?false:null,downloadable:null,downloadUrl:null,author,description,fileSize:body.match(/File size\s+([0-9.,]+\s*(?:KB|MB|GB))/i)?.[1]||null,brand:brandOf(title),game,year:yearMatch?Number(yearMatch[1]):null,vehicleClass:/\b(suv|crossover|4x4)\b/i.test(title)?'SUV':/\b(race|racing|gt3|gt4|drift|rally|formula)\b/i.test(`${title} ${description||''}`)?'Race Car':'Car',score:candidate.relevance+6}}catch{return null}}
export async function searchOvertake(query,limit=60){const tags=tagCandidates(query),all=[],seen=new Set();let pagesFetched=0;for(const tag of tags){for(let page=1;page<=4;page+=1){const url=`${BASE}/tags/${encodeURIComponent(tag)}/${page>1?`?page=${page}`:''}`;let html;try{({html}=await fetchHtml(url))}catch{break}pagesFetched++;const found=parseTag(html,query);if(!found.length&&page>1)break;for(const item of found)if(!seen.has(item.sourceUrl)){seen.add(item.sourceUrl);all.push(item)}}}const candidates=all.sort((a,b)=>b.relevance-a.relevance).slice(0,Math.min(limit*2,80));const detailed=await Promise.all(candidates.map(item=>limiter(()=>enrich(item))));return{results:detailed.filter(Boolean).slice(0,limit),pagesFetched}}
