const tagSlug = value => String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').split(/\s+/).filter(Boolean).pop()?.replace(/[^a-z0-9-]+/g, '-') || 'car'

export const providers = [
  { id: 'rigmodels', name: 'RigModels', type: '3d-models', freeCatalog: true, pagination: true, baseUrl: 'https://rigmodels.com', buildUrl: q => `https://rigmodels.com/index.php?searchkeyword=${encodeURIComponent(q)}` },
  { id: 'free3d', name: 'Free3D', type: '3d-models', pagination: true, baseUrl: 'https://free3d.com', buildUrl: q => `https://free3d.com/3d-models/${encodeURIComponent(q.trim().replace(/\s+/g, '-'))}` },
  { id: '3drush', name: '3D Rush', type: '3d-models', pagination: true, baseUrl: 'https://3drush.com', buildUrl: q => `https://3drush.com/?s=${encodeURIComponent(q)}` },
  { id: 'brasil-simulator-mods', name: 'Brasil Simulator Mods', type: 'game-mods', freeCatalog: true, pagination: true, baseUrl: 'https://brasilsimulatormods.com', buildUrl: q => `https://brasilsimulatormods.com/?s=${encodeURIComponent(q)}` },
  { id: 'overtake', name: 'OverTake.gg', type: 'game-mods', pagination: true, baseUrl: 'https://www.overtake.gg', buildUrl: q => `https://www.overtake.gg/search/?q=${encodeURIComponent(q)}` },
  { id: 'assettomods', name: 'Assetto Mods', type: 'game-mods', defaultGame: 'Assetto Corsa', pagination: true, baseUrl: 'https://assettomods.com', buildUrl: q => `https://assettomods.com/?s=${encodeURIComponent(q)}` },
  { id: 'moddb', name: 'ModDB', type: 'game-mods', freeCatalog: true, pagination: true, baseUrl: 'https://www.moddb.com', buildUrl: q => `https://www.moddb.com/search?q=${encodeURIComponent(`${q} car vehicle`)}` },
  { id: 'assettohub', name: 'Assetto Hub', type: 'game-mods', freeCatalog: true, defaultGame: 'Assetto Corsa', pagination: true, baseUrl: 'https://www.assettohub.com', buildUrl: q => `https://www.assettohub.com/?s=${encodeURIComponent(q)}` },
  { id: 'ets2lt', name: 'ETS2.lt', type: 'game-mods', freeCatalog: true, defaultGame: 'Euro Truck Simulator 2', pagination: true, baseUrl: 'https://ets2.lt', buildUrl: q => `https://ets2.lt/en/?s=${encodeURIComponent(q)}` },
  { id: 'vosan', name: 'VOSAN', type: 'game-mods', defaultGame: 'Assetto Corsa', pagination: true, baseUrl: 'https://vosan.co', buildUrl: q => `https://vosan.co/explore?search=${encodeURIComponent(q)}` },
  { id: 'sketchfab', name: 'Sketchfab', type: '3d-models', adapter: 'sketchfab', baseUrl: 'https://sketchfab.com', buildUrl: q => `https://sketchfab.com/search?type=models&q=${encodeURIComponent(q)}&features=downloadable` },
  { id: 'cgtrader', name: 'CGTrader', type: '3d-models', pagination: true, baseUrl: 'https://www.cgtrader.com', buildUrl: q => `https://www.cgtrader.com/3d-models/${encodeURIComponent(tagSlug(q))}` },
  { id: 'done3d', name: 'Done3D', type: '3d-models', pagination: true, baseUrl: 'https://done3d.com', buildUrl: q => `https://done3d.com/?s=${encodeURIComponent(q)}` },
  { id: '3dsky', name: '3DSky', type: '3d-models', pagination: true, baseUrl: 'https://3dsky.org', buildUrl: q => `https://3dsky.org/3dmodels?search=${encodeURIComponent(`${q} car`)}` },
  { id: 'free3dio', name: 'Free3D.io', type: '3d-models', pagination: true, baseUrl: 'https://free3d.io', buildUrl: q => `https://free3d.io/?q=${encodeURIComponent(`${q} vehicle`)}` },
  { id: 'vertex-warehouse', name: 'Vertex Warehouse', type: '3d-models', freeCatalog: true, adapter: 'vertex', browseUrl: 'https://www.vertex-warehouse.com/models', pagination: true, baseUrl: 'https://www.vertex-warehouse.com', buildUrl: q => `https://www.vertex-warehouse.com/search?query=${encodeURIComponent(q)}&type=fts` },
  { id: 'mediafire-rr3', name: 'MediaFire · Real Racing 3', type: '3d-models', freeCatalog: true, defaultGame: 'Real Racing 3', adapter: 'collection', collectionUrl: 'https://www.mediafire.com/folder/w7e2zubiwwr38/Real_Racing_3', baseUrl: 'https://www.mediafire.com', buildUrl: () => 'https://www.mediafire.com/folder/w7e2zubiwwr38/Real_Racing_3' },
  { id: 'open3dlab', name: 'Open3DLab', type: '3d-models', freeCatalog: true, adapter: 'collection', collectionUrl: 'https://open3dlab.com/list/dd0e6ac2-5965-456d-8c4d-b06a81c64782/', extraCollectionUrls: ['https://open3dlab.com/list/0a696900-05a3-4394-a0cc-0a964e5fec89/'], baseUrl: 'https://open3dlab.com', buildUrl: () => 'https://open3dlab.com/list/dd0e6ac2-5965-456d-8c4d-b06a81c64782/' },
  { id: 'vk-3d-car-models', name: 'VK · 3D Car Models', type: '3d-models', freeCatalog: true, adapter: 'collection', collectionUrl: 'https://vk.ru/3d_car_models', baseUrl: 'https://vk.ru', buildUrl: () => 'https://vk.ru/3d_car_models' },
  { id: '3dwarehouse', name: 'SketchUp 3D Warehouse', type: '3d-models', freeCatalog: true, pagination: true, baseUrl: 'https://3dwarehouse.sketchup.com', buildUrl: q => `https://3dwarehouse.sketchup.com/search/?q=${encodeURIComponent(`${q} car vehicle`)}` },
]
